[toolchain]
anchor_version = "0.29.0"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
spl_governance = "6WELr8KBZV5uTYqn54nrpCAYN9uEJWWip2toY67ByhqU"
spl_governance_chat = "8s9ViAVw4pSWDhyQg5dEY8Yyka9zvEccF513syhceKhW"
spl_stake_pool = "AkfzmaednX1Ve34SP3rNSyPjaZ96J6UVeZR4Yzu9hQXh"
spl_token = "HzcnqsbqoA5xguYLCTvFzS5z9GUMvz4Axy8d5fnzcYif"
spl_token_2022 = "FLq5RqqHeHthk7yKtn7E3vdqaFhpNNi9suB6NNXBrrdA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["governance/program", "governance/chat/program", "stake-pool/program", "token/program", "token/program-2022"]
exclude = ["account-compression/"]
